### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by EsterWeiss** [skyvar/registration#1]
The task is to create a Dockerfile that builds a container with the ffmpeg package by image and create an entrypoint for it
The explanation may not be perfect yet...

**Comment by bdsoha** [comment]
@EsterWeiss you have been assigned. Good luck!

**Comment by bdsoha** [comment]
Please update your user profile based on:
> Register a GitHub account with your corporate email address (i.e. @skyvar.co.il) and your full first and last name in English.

**Comment by EsterWeiss** [comment]
Should the solution be something like a Dockerfile that I write myself?

**Comment by bdsoha** [comment]
The solution shouldn't be *like*, it should be ***exactly***.

You are to create a `Dockerfile` of your own with the required additions.

**Comment by EsterWeiss** [comment]
[](url)

**Comment by bdsoha** [comment]
@EsterWeiss Why did you close this? 
Did you submit a *pull request*?
Was the *pull request* merged?

**Comment by EsterWeiss** [comment]
I accidentally closed
I'm trying to upload a document now and share

**Comment by bdsoha** [comment]
No need to share any documents here.
Open a *pull request* to submit your solution.

**Comment by EsterWeiss** [comment]
Before I investigate how to create a pull request (I haven't used git yet)
I would love to receive an opinion on whether I completed the task
I created a Dockerfile document

`FROM ubuntu:latest

RUN apt-get update && apt-get install -y ffmpeg

ENTRYPOINT ["ffmpeg"]`

When running the command: docker build -t my-ffmpeg-image . In the command line, an image and a container were created for me
Are there parts missing in the answer or all I have to do is submit the Dockerfile

**Comment by bdsoha** [comment]
I am also not going to review partial solutions here.
Please open a pull request if you feel that you have completed the task.

Any subsequent changes will be posted there.

**Comment by bdsoha** [comment]
What I could say is, you are off to a good start.

You can *(and should)* use [Markdown](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) to write comments and docs.

> **Note**
> By adding 3-backticks *```* and then the language you are using, you can magically add syntax highlighting. More details [here](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code). 

Your code would be displayed as below:

```dockerfile
FROM ubuntu:latest

RUN apt-get update && apt-get install -y ffmpeg

ENTRYPOINT ["ffmpeg"]
```
