### ISSUE TITLE
Coordinate Conversion

### ISSUE THREAD

**Issue by chananaimen** [skyvar/registration#11]
Use conversion libraries and functions such as convert and more

**Comment by bdsoha** [comment]
@chananaimen you have been assigned. Good luck!

**Comment by bdsoha** [comment]
Please update your user profile based on:
> Register a GitHub account with your corporate email address (i.e. @skyvar.co.il) and your full first and last name in English.

**Comment by chananaimen** [comment]
This can be done by calculating and converting int
The whole number is the cost of the cost.
Then we subtract the whole number from the number and multiply the remaining by 60 and convert it to int the minutes.
And the seconds by subtracting the whole minutes and multiplying again by 60?

**Comment by chananaimen** [comment]
אין מידע באינטרנט שנפתח בנושא.
הכל חסום.
יש רק מידע מועט על excel

**Comment by bdsoha** [comment]
> אין מידע באינטרנט שנפתח בנושא. הכל חסום. יש רק מידע מועט על excel

Please stick to English.

**Comment by bdsoha** [comment]
> This can be done by calculating and converting int The whole number is the cost of the cost. Then we subtract the whole number from the number and multiply the remaining by 60 and convert it to int the minutes. And the seconds by subtracting the whole minutes and multiplying again by 60?

Are you asking? Or are you explaining?

**Comment by bdsoha** [comment]
The equation is as follows:

![image](https://user-images.githubusercontent.com/4192777/224971832-71c7f43a-7566-46b1-835d-53c0174f8e58.png)

**Comment by chananaimen** [comment]
i do function that recieve dd :
do it good?:
var absDd = Math.abs(dd);
  var deg = Math.floor(absDd);
  var frac = absDd - deg;
  if(frac!=0)
  {
    frac=frac*60;
    var min = Math.floor(frac) ;
    var sec = frac - min ;
  if(sec!=0)
    {
      sec =(Math.floor(Math.round(sec * 6000)))/100;
     return deg + " degrees " + min + " minutes " + sec + ' second ' + dir;
    }
 return  deg + " degrees " + min + " minutes " + dir;
  }
  
  return  deg + " degrees " + dir;

**Comment by chananaimen** [comment]
What does the figure 'w' written in the example mean in decimal points?

**Comment by bdsoha** [comment]
> What does the figure 'w' written in the example mean in decimal points?

**N:** North
**E:** East
**S:** South
**W:** West

**Comment by bdsoha** [comment]
Off to a good start.

You can *(and should)* use [Markdown](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) to write comments and docs.

> **Note**
> By adding 3-backticks *```* and then the language you are using, you can magically add syntax highlighting. More details [here](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code). 

Your code would be displayed as below:

```js
var absDd = Math.abs(dd);
var deg = Math.floor(absDd);
var frac = absDd - deg;
if(frac!=0)
{
frac=frac*60;
var min = Math.floor(frac) ;
var sec = frac - min ;
if(sec!=0)
{
sec =(Math.floor(Math.round(sec * 6000)))/100;
return deg + " degrees " + min + " minutes " + sec + ' second ' + dir;
}
return deg + " degrees " + min + " minutes " + dir;
}

return deg + " degrees " + dir;
```

**Comment by chananaimen** [comment]
Use markdown for order?

**Comment by chananaimen** [comment]
My code is:

function convertFromDDToDms(dd, isLng) {
  var dir;
    if(dd<0)
    {
      if(isLng)
      {
        dir='W';
      }
      else
      {
        dir='S'
      }
    }
    else
    {
      if(isLng)
      {
        dir='E';
      }
      else
      {
        dir='N'
      }
    }

  var absDd = Math.abs(dd);
  var deg = Math.floor(absDd);
  var temp = absDd - deg;
  if(temp!=0)
  {
    temp=temp*60;
    var min = Math.floor(temp) ;
    var sec = temp - min ;
  if(sec!=0)
    {
      sec =(Math.floor(Math.round(sec * 6000)))/100;
     return deg + " degrees " + min + " minutes " + sec + ' second ' + dir;
    }
 return  deg + " degrees " + min + " minutes " + dir;
  }
  
  return  deg + " degrees " + dir;
}

console.log(convertFromDDToDms(34.0522,false));

**Comment by bdsoha** [comment]
You shouldn't be posting code snippets as plaintext.

**Comment by bdsoha** [comment]
I am also not going to review partial solutions.

**Comment by chananaimen** [comment]
## ok

**Comment by chananaimen** [comment]
## function convertFromDDToDms(dd, isLng)
 {
  var dir;
    if(dd<0)
    {
      if(isLng)
      {
        dir='W';
      }
      else
      {
        dir='S'
      }
    }
    else
    {
      if(isLng)
      {
        dir='E';
      }
      else
      {
        dir='N'
      }
    }

-  var absDd = Math.abs(dd);
-  var deg = Math.floor(absDd);
-  var temp = absDd - deg;
  if(temp!=0)
  {
    temp=temp*60;
    var min = Math.floor(temp) ;
    var sec = temp - min ;
  if(sec!=0)
    {
      sec =(Math.floor(Math.round(sec * 6000)))/100;
     return deg + " degrees " + min + " minutes " + sec + ' second ' + dir;
    }
 return  deg + " degrees " + min + " minutes " + dir;
  }
  
  return  deg + " degrees " + dir;
}

console.log(convertFromDDToDms(34.0522,false));

**Comment by bdsoha** [comment]
I am also not going to review partial solutions. 
Please open a *pull request* if you feel that you have completed the task.

**Comment by chananaimen** [comment]
#function convertFromDDToDms(dd, isLng) {
  var dir;
##    if(dd<0)
    {
      if(isLng)
      {
        dir='W';
      }
      else
      {
        dir='S'
      }
    }
    else
    {
      if(isLng)
      {
        dir='E';
      }
      else
      {
        dir='N'
      }
    }

 - var absDd = Math.abs(dd);
  - var deg = Math.floor(absDd);
  - var temp = absDd - deg;
  if(temp!=0)
  {
    - temp=temp*60;
    - var min = Math.floor(temp) ;
    - var sec = temp - min ;
  if(sec!=0)
    {
      sec =(Math.floor(Math.round(sec * 6000)))/100;
    ** return deg + " degrees " + min + " minutes " + sec + ' second ' + dir;**
    }
**return  deg + " degrees " + min + " minutes " + dir;**
  }
  
  **return  deg + " degrees " + dir;**
}

console.log(convertFromDDToDms(34.0522,false));

**Comment by bdsoha** [comment]
**I am also not going to review partial solutions.
Please open a pull request if you feel that you have completed the task.**

**Comment by bdsoha** [comment]
@chananaimen 🛑 🤚 Please stop posting code snippets here *(especially considering their lack of style)*

**Comment by chananaimen** [comment]
function will receive a decimal value and convert or should the function receive an object like json with a place name and some decimal points and insert the conversion into it in the form of an array within an array?

**Comment by bdsoha** [comment]
> function will receive a decimal value and convert or should the function receive an object like json with a place name and some decimal points and insert the conversion into it in the form of an array within an array?

Up to you, as long as the *developer experience* is easy to use and intuitive.

**Comment by chananaimen** [comment]
i want to do 'clone' : PS Microsoft.PowerShell.Core\FileSystem::\\svdc2\NetFolder\Docs\myconvertdd> git clone https://github.com/skyvar/registration.git
Cloning into 'registration'...
fatal: unable to access 'https://github.com/skyvar/registration.git/': SSL certificate problem: unable to get local issuer certificate and i hava error atal: unable to access 'https://github.com/skyvar/registration.git/': SSL certificate problem: unable to get local issuer certificate 
I understand that this is a problem with the firewall and permissions.
How do I handle it?

**Comment by bdsoha** [comment]
Regarding your SSL issue:
https://netfree.link/wiki/Installation_of_certificate_in_GIT

**Comment by chananaimen** [comment]
i get code but i forget password i press Reset your password but i get That address is either invalid, not a [verified primary email](https://docs.github.com/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/changing-your-primary-email-address) or is not associated with a [personal user account](https://docs.github.com/get-started/learning-about-github/types-of-github-accounts). Organization [billing emails](https://docs.github.com/billing/managing-your-github-billing-settings/setting-your-billing-email) are only for notifications
what i do?

**Comment by bdsoha** [comment]
I don't know how to help you... 
Your issue is unrelated to the current assignment.
