### ISSUE TITLE
FastAPI

### ISSUE THREAD

**Issue by esterlev23** [skyvar/registration#2]
I will create a FastAPI:
Deploy a simple http server with two endpoints:
An endpoint that appends a json payload to a local file.
An endpoint that returns the last 10 payloads from the persisted file.

I will work according to the following guide step by step:
https://fastapi.tiangolo.com/

**Comment by bdsoha** [comment]
@esterlev23 you have been assigned. Good luck!

**Comment by esterlev23** [comment]
I tried but apparently my name is popular so he didn't let me register with just a first and last name

**Comment by bdsoha** [comment]
> I tried but apparently my name is popular so he didn't let me register with just a first and last name

I am not referring to your *username*, I am referring to your profile.
Go to https://github.com/esterlev23 and click `Edit Profile`.

**Comment by esterlev23** [comment]
Updated

**Comment by esterlev23** [comment]
We have now been instructed to work through the Docker.
I've been working through the command line and I'm almost done.
I already have a Festafi server running, I need to finish messing with the file.
Should I change and start all over again through Docker?

**Comment by bdsoha** [comment]
Using Docker does not require you to *change* or *rewrite* your code.
Your Python code remains the same.

**Comment by bdsoha** [comment]
You can mount a local host directory into the running container using `-v %cd%:/app`. This will mount the current working directory into `/app`.

Remember to also publish the required port for FastAPI.

**Comment by esterlev23** [comment]
I finished the assignment.
I wrote a Fastapi that works great, gets Jason adds to a file and returns the last 10.
I closed it as an image with a Dockerfile and requirements file and ran it on a container
From now it supposed to run on port 8000, but for some reason I don't see it running...
Do you know what the problem could be?

**Comment by bdsoha** [comment]
Provide your `docker run ...` statement.
Most probably has to do with the `--host` flag of the server listening on a local *(inside docker)* bus.

**Comment by esterlev23** [comment]
I solved the problem!
The file was just accidentally deleted...

What's left for me is actually to upload to git

**Comment by esterlev23** [comment]
I think I'm done, did I do it right?
