### ISSUE TITLE
Password Strength

### ISSUE THREAD

**Issue by FridaPshitik** [skyvar/registration#4]
Write a certain function that checks certain data about the received password and returns whether it is correct

**Comment by bdsoha** [comment]
@FridaPshitik you have been assigned. Good luck!

**Comment by bdsoha** [comment]
Please update your user profile based on:
> Register a GitHub account with your corporate email address (i.e. @skyvar.co.il) and your full first and last name in English.

**Comment by bdsoha** [comment]
@FridaPshitik Any updates? Questions?

**Comment by FridaPshitik** [comment]
I'm already uploading to GIT

**Comment by bdsoha** [comment]
Make sure to create a `feature/***` branch from the `main`.
