### ISSUE TITLE
VitePress

### ISSUE THREAD

**Issue by SaraLitman** [skyvar/registration#5]
im going to deploy a simple VitePress instance with two pages according to https://www.codementor.io/@burhanuddinahmed/deploying-vitepress-to-github-pages-1ft7mbf6lc
and then create two pages:
A landing page containing information a fake software tool from your imagination.
An installation guide for the above mentioned tool.

**Comment by bdsoha** [comment]
@SaraLitman you have been assigned. Good luck!

**Comment by bdsoha** [comment]
Please update your user profile based on:
> Register a GitHub account with your corporate email address (i.e. @skyvar.co.il) and your full first and last name in English.

**Comment by SaraLitman** [comment]
I'm looking for an image to work with VitePress and i dont found,
where should i find this?

**Comment by bdsoha** [comment]
What language is required to use VitePress? The answer to that question will also answer your question.

**Comment by bdsoha** [comment]
[`node:16.19.1-buster`](https://hub.docker.com/layers/library/node/16.19.1-buster/images/sha256-79931b9515da405e0c3e0eccc755299d72d6112c0cc80e8accd7498a85e7d03d?context=explore)

**Comment by SaraLitman** [comment]
that's the image?

**Comment by bdsoha** [comment]
The [documentation](https://vitepress.dev/guide/getting-started#prerequisites) states the following:

> [Node.js](https://nodejs.org/) version 16 or higher.

Since you are using Docker, I would expect you to search [hub.docker.com](https://hub.docker.com/search?q=node) for *"node"*. At which point you would begin to look for the specific version needed. In your case, something `>=16`.

**Comment by bdsoha** [comment]
You can mount a local host directory into the running container using `-v %cd%:/app`. This will mount the current working directory into `/app`.

Remember to also publish the required port for VitePress.

**Comment by SaraLitman** [comment]
I see that the VitePress is not so simple to understand in 0ne day,
may I do the task with another UI tool?

**Comment by bdsoha** [comment]
Unfortunately not.
The suggested tasks all provide the same level of *self-learning*.

VitePress itself *(as mentioned in their tag-line)*:
> Simple, powerful, and fast

There is no reason why a simple scaffolding should take more than 1 day.

**Comment by bdsoha** [comment]
@SaraLitman Any questions? Updates?

**Comment by SaraLitman** [comment]
I was typing a question when you sent me your message- I Have an image, the log of the container looks good, but by runnning the webpage I have a problem to connect. what should I do?

**Comment by bdsoha** [comment]
Did you map any port to the image?
What does your `docker run...` command look like?

**Comment by SaraLitman** [comment]
docker run -p 8080:80 my-image

**Comment by bdsoha** [comment]
What port is *VitePress* publishing by default? Is it not `5173`?

**Comment by SaraLitman** [comment]
the command has to be 'docker run -p 5173:80 my-image'?
in my DockerFileI have 'EXPOSE 8000' 
and in the Yaml file I have: '  ports:
      - "8000:8000"'
      (I changed it becouse I had problems with the port,)
 is it wrong?
I Have to change/add something? this is the direction or something else?

**Comment by bdsoha** [comment]
The ports should be swapped, and also its not suggested to use port `80` on your host:

```sh
docker run -it --rm -p 80:5173 my-image
```

**Comment by SaraLitman** [comment]
thanks, I will try to change it correctly

**Comment by SaraLitman** [comment]
docker run -it --rm -p 8080:5173 my-image
I try to access the VitePress site by going to http://localhost:8080 and I get an error: 
The connection has been terminated
The connection to the server will be initialized while the page is loading.
what could be the problem?

**Comment by bdsoha** [comment]
What does your `my-image` contain? What is the entrypoint?

**Comment by bdsoha** [comment]
Are you running `npm run docs:preview`?

**Comment by SaraLitman** [comment]
thats my run commands on the DockerFile: RUN npm install
RUN npm run build
Have I to add RUN npm run docs:preview
?

**Comment by SaraLitman** [comment]
FROM node:16-alpine3.14

WORKDIR /app

COPY . .

RUN npm install
RUN npm run build


EXPOSE 5173

CMD ["npm", "run", "serve", "--", "-s", "/app/.vitepress/dist"]

**Comment by bdsoha** [comment]
You are mixing and matching commands.
What's the value of  `"serve"` in `package.json`?

**Comment by bdsoha** [comment]
Your `package.json` should look something like this:

```json
{
  ...
  "main": "index.js",
  "scripts": {
    "docs:dev": "vitepress dev docs",
    "docs:build": "vitepress build docs",
    "docs:preview": "vitepress preview docs"
  },
  "devDependencies": {
    "vitepress": "^1.0.0-alpha.29",
    "vue": "^3.2.45"
  }
}
```

**Comment by SaraLitman** [comment]
I dont have a index.js file in my project,
 by looking in google I fount that my enrypoint has to be ["npm", "run", "serve"]- is it wrong?
I Have to create a index.js file in my projet? and there I hava to wrote this command?

**Comment by bdsoha** [comment]
Did you scaffold the project using `npx vitepress init`?

**Comment by SaraLitman** [comment]
no, I got this error by running npx vitepress init:
npx : The term 'npx' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try 
again.
At line:1 char:1
+ npx vitepress init
+ ~~~
    + CategoryInfo          : ObjectNotFound: (npx:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
So like the solution I found on Google-
I built my project according to the instructions I found on Google in this way:
docs(folder)
   ->index.md
  -> installation.md
node_modules(folder)
docker-compose.yaml
DockerFile
package.json
I understand that something is wrong with my structure,
so How can I build the project with the 'npx vitepress init' command?

**Comment by bdsoha** [comment]
Do you have `npx` installed on the host machine?
Do you need it installed? *(Answer: No)*.

Utilize docker to scaffold your project *(in a clean directory)*:

```sh
docker run -it --rm -v $PWD:/app --entrypoint bash node:16-alpine3.14
```

Then inside the container:

```sh
cd /app
npx vitepress init 
```

**Comment by bdsoha** [comment]
Don't use firefox and make sure you are using the correct ports:
- `5173` for development
- `5000` for publication

**Comment by bdsoha** [comment]
No, I meant during `docker run` of the built container.

**Comment by SaraLitman** [comment]
I'm going out.
I will upload what I have done so far at the beginning of the next working day.
(Meanwhile I ran into the firewall again)

**Comment by SaraLitman** [comment]
I ask to make sure I understood correctly:
I created a project on a container created by running the image of Vitapress
Now in order to save the project and upload it to git, I should create a new image based on this image, right?
And the way to do that is to create a Dockerfile in my project folder and run the image build in command, right?

**Comment by bdsoha** [comment]
Correct.

**Comment by SaraLitman** [comment]
To upload the image from Docker to GitHub do I need to have DockerHub installed on my computer?

**Comment by bdsoha** [comment]
Until now, you have been running docker commands, which means docker is installed.
You need to provide a `Dockerfile` as part of your solution *(it is nothing more than a text file)*.

**Comment by SaraLitman** [comment]
I uploaded to git, waiting for comments...

**Comment by bdsoha** [comment]
> I uploaded to git, waiting for comments...

I already commented on the PR before your wrote this.
