### ISSUE TITLE
Python Docker

### ISSUE THREAD

**Issue by ShaindyBorzikowsky** [skyvar/registration#6]
Install Pyhton on busybox container taht i will run
i have to keep it in sleep and to run more cmd and retrieving the host

**Comment by bdsoha** [comment]
@ShaindyBorzikowsky you have been assigned. Good luck!

**Comment by bdsoha** [comment]
Please update your user profile based on:
> Register a GitHub account with your corporate email address (i.e. @skyvar.co.il) and your full first and last name in English.

**Comment by ShaindyBorzikowsky** [comment]
Now its OK?

**Comment by bdsoha** [comment]
> Now its OK?

Email...

**Comment by ShaindyBorzikowsky** [comment]
and now?

**Comment by ShaindyBorzikowsky** [comment]
this is my python code:

import docker

client = docker.from_env()

container = client.containers.run("busybox", "sleep 3600", detach=True)

result = container.exec_run("hostname")
print(result.output.decode().strip())

container.stop()
container.remove()

![image](https://user-images.githubusercontent.com/127834811/225009930-8d658935-9023-4e6f-8f11-5546c4ca2733.png)

Am I in the right direction?

**Comment by bdsoha** [comment]
Off to a good start.

> You can *(and should)* use [Markdown](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) to write comments and docs.

> **Note**
> By adding 3-backticks *```* and then the language you are using, you can magically add syntax highlighting. More details [here](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code).

**Comment by ShaindyBorzikowsky** [comment]
> I have an error on the `import docker`, it claims that docker is not installed even though it is installed and running.
When I try to pip install docker,
I get an error that it doesn't know the pip command.
I would appreciate your help because I'm stuck with this since this morning...

**Comment by bdsoha** [comment]
Where are you running the commands?
On the host machine?
Or in docker?

**Comment by bdsoha** [comment]
`pip` is not installed on the host.
You are supposed to utilize `docker` to run the commands.
In your case, you need an image that contains both `docker` and `python`.

**Comment by bdsoha** [comment]
Start with a [`python`](https://hub.docker.com/_/python) image from docker-hub.
Within the running container, you can run `pip install ....`

**Comment by bdsoha** [comment]
Make sure to run the command with an alternate `--entrypoint`, and be sure to mount the docker socket.

**Comment by ShaindyBorzikowsky** [comment]
I was totally confused.
At first, I opened a Python file in VSCODE, and started writing a DOCKERFILE, but according to what you wrote, it seemed to me that I was working incorrectly, I tried to run a container that contains a Python image on the command line, but I don't think I did it correctly,
I will have a bit of a salad when the spiker comes into action and whether it is necessary to act with it in the first place

**Comment by bdsoha** [comment]
The code you submitted works perfectly. The only issue is with your development setup.
You are supposed to used `docker` during development as well, as to guarantee that your code is portable and will work on any machine.

If you decide to use *VSCode*, then you have two options when integrating with docker:
1. Use [Developing inside a Container](https://code.visualstudio.com/docs/devcontainers/containers). Which was provided on Monday together with the docker tutorial.
2. Manually execute a docker container and map all necessary ports, volumes, and entrypoints.

Your specific task is slightly more complicated because from within the docker container you require access to the docker engine on the host. This is easily handled on Linux by mounting the docker socket into the container as a volume.

The following command would execute your code on Linux:
```bash
docker run -it --rm --entrypoint bash -v $(pwd):/app -v /var/run/docker.sock:/var/run/docker.sock python
```

**Comment by ShaindyBorzikowsky** [comment]
I run this command and the response was: `docker: invalid reference format`
I try many ways, 
In the end I ran this command:
`docker run -it --rm --entrypoint sh -v /var/run/docker.sock:/var/run/docker.sock -v C:\Users\ShaindyB\Documents\GitHub\feature-PythonDocker/app:/app docker:dind`
and check with `ls`
the response was:

 `/var/run/docker.sock`
now I tried to pip install, but I couldn't,
So I installed the pip install option (`apk add py-pip`)
and it didn't help enough,
this command help: `pip install --upgrade pip`
but when I try to `cp` my python code into the container,
I get an error saying that I cannot copy between containers
What to do?
I have already checked the path of the file and the name of the container,
I already want to finish so much!!!

**Comment by bdsoha** [comment]
No need for `docker:dind`.

Are you using `cmd` or `powershell`?

**Comment by ShaindyBorzikowsky** [comment]
powershell

**Comment by bdsoha** [comment]
Try the following:

```sh
docker run -it --rm --entrypoint bash -v $PWD:/app -v ////./pipe/docker_engine:/var/run/docker.sock python
```

**Comment by bdsoha** [comment]
### Good to Know

To get your *present working directory*:
- PowerShell: `$PWD`
- cmd: `%cd%`
- sh: `pwd`

**Comment by bdsoha** [comment]
I just ran the command from [here](https://github.com/skyvar/registration/issues/6#issuecomment-1471498508) on a Windows machine *(without WSL2)*. Please let me know if it works.

**Comment by ShaindyBorzikowsky** [comment]
It created a container but in the meantime I could not run in it `pip install docker`

**Comment by bdsoha** [comment]
From within the `python` container, you can't run `pip`?

**Comment by ShaindyBorzikowsky** [comment]
Right

**Comment by bdsoha** [comment]
What is the error?

**Comment by ShaindyBorzikowsky** [comment]
'Could not fetch URL https://pypi.org/simple/docker/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/docker/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)'))) - skipping
ERROR: Could not find a version that satisfies the requirement docker (from versions: none)
ERROR: No matching distribution found for docker
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)'))) - skipping'

(there are also wrongs)

**Comment by bdsoha** [comment]
`pip` is working as expected. There is an issue with the *SSL Certificate* due to _NetFree_.

Add the following to the end of the `pip install ...` command:
```sh
pip install .... --trusted-host pypi.python.org --trusted-host python.org --trusted-host files.pythonhosted.org
```

**Comment by ShaindyBorzikowsky** [comment]
Can you help me with [this](https://github.com/skyvar/registration/issues/6#:~:text=No%2C%20I%20got%20the%20same%20response%20again)?

**Comment by bdsoha** [comment]
Please post the entire `pip` command *(run from within the container)* here.

**Comment by ShaindyBorzikowsky** [comment]
`pip install docker. --trusted-host pypi.python.org --trusted-host python.org --trusted-host files.pythonhosted.org`

**Comment by ShaindyBorzikowsky** [comment]
I update the command now

**Comment by bdsoha** [comment]
Last try *(changed `python.org` to `pypi.org`)*:

```sh
pip install --trusted-host pypi.org --trusted-host pypi.python.org --trusted-host files.pythonhosted.org docker
```

**Comment by ShaindyBorzikowsky** [comment]
It works!
By the way, why does he keep suggesting I use virtual environment?

**Comment by bdsoha** [comment]
`venv` or virtual environments are crucial when working on the host machine in order to provide _separation_ and _portability_ of projects. When using `docker`, you delegate the separation control without the need for a `venv`.

**Comment by ShaindyBorzikowsky** [comment]
Now I tried to run:
`docker ps`
But suddenly I get this error:
'bash: docker: command not found'
I don't understand why?

**Comment by bdsoha** [comment]
Is `docker` shell command installed in the container?
Does it need to be installed? *(Answer: No)*.

Try running your python code.

**Comment by ShaindyBorzikowsky** [comment]
It works!
when i run  this command:
 `python /app/dockerPython.py` 
I get the host!
now i need to upload my fork to GitHub?

**Comment by bdsoha** [comment]
Yes

**Comment by ShaindyBorzikowsky** [comment]
I'm asking because I actually only have a Python file that in order to run it in Docker I ran the command that runs a container, then pip install docker, then I ran the Python file that is currently inside a Python container
So what do I have to upload besides the Python file?
Should I upload the code file and write in the README which commands to run for it to work?

**Comment by bdsoha** [comment]
You can either create a custom `Dockerfile` or upload a a document describing the needed steps to run the code.
