### ISSUE TITLE
Numpy

### ISSUE THREAD

**Issue by RivkaZishinski** [skyvar/registration#7]
Given an image of choosing, create histogram of RGB colors found in the image using numpy.

**Comment by bdsoha** [comment]
Please update your user profile based on:
> Register a GitHub account with your corporate email address (i.e. @skyvar.co.il) and your full first and last name in English.

**Comment by bdsoha** [comment]
@RivkaZishinski you have been assigned. Good luck!

**Comment by RivkaZishinski** [comment]
i editted my profile

**Comment by bdsoha** [comment]
> i editted my profile

Have one more go...
- First name
- Last name
- Email

**Comment by bdsoha** [comment]
```diff
# Don't forget the space between your name
-RivkaTzishinsky
+Rivka Tzishinsky
# ----^----------
```

**Comment by RivkaZishinski** [comment]
i change

**Comment by RivkaZishinski** [comment]
I tried to work on the working environment of the Git,
 and after it works, i will add it to docker with Dockerfile, 
it is good way?
I got stuck Still working with the python on VS

**Comment by bdsoha** [comment]
You are never supposed to add a `.git` directory to a `Dockerfile`.
You are supposed to provide the source code of your solution on a separate branch, with any required documentation or descriptions *(when needed)*.

**Comment by RivkaZishinski** [comment]
1.this is my code and i want the intent how do i upload it to the git  i try and get this-
PS C:\Users\RivkaZ\Documents\GitHub\numpy> git push origin histogram-rgb-by-numpy
fatal: unable to access 'https://github.com/RivkaZishinski/numpy.git/': SSL certificate problem: unable to get local issuer certificate.

2.the result of it code is vesual it is good?



`import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from PIL import Image

img = Image.open('C:\images\light_blue.png')

rgb_array = np.array(img)

pixel_array = rgb_array.reshape(-1, 3)

red = pixel_array[:, 0]
green = pixel_array[:, 1]
blue = pixel_array[:, 2]

fig = plt.figure()
ax = fig.add_subplot(projection='3d')
hist, edges = np.histogramdd(pixel_array, bins=(256, 256, 256), range=((0, 256), (0, 256), (0, 256)))

x, y, z = np.meshgrid(edges[0][:-1], edges[1][:-1], edges[2][:-1], indexing='ij')

ax.scatter(x.flatten(), y.flatten(), z.flatten(), c=hist.flatten(), cmap='plasma')
plt.title("Histogram of All Colors")
plt.show()

`

**Comment by bdsoha** [comment]
I am not going to review partial solutions here.
Please open a pull request if you feel that you have completed the task.

You can *(and should)* use [Markdown](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) to write comments and docs.

> **Note**
> By adding 3-backticks *```* and then the language you are using, you can magically add syntax highlighting. More details [here](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code). 

Your code would be displayed as below:

```python
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from PIL import Image

img = Image.open('C:\images\light_blue.png')

rgb_array = np.array(img)

pixel_array = rgb_array.reshape(-1, 3)

red = pixel_array[:, 0]
green = pixel_array[:, 1]
blue = pixel_array[:, 2]

fig = plt.figure()
ax = fig.add_subplot(projection='3d')
hist, edges = np.histogramdd(pixel_array, bins=(256, 256, 256), range=((0, 256), (0, 256), (0, 256)))

x, y, z = np.meshgrid(edges[0][:-1], edges[1][:-1], edges[2][:-1], indexing='ij')

ax.scatter(x.flatten(), y.flatten(), z.flatten(), c=hist.flatten(), cmap='plasma')
plt.title("Histogram of All Colors")
plt.show()
```

**Comment by bdsoha** [comment]
Regarding your SSL issue:
https://netfree.link/wiki/Installation_of_certificate_in_GIT

**Comment by RivkaZishinski** [comment]
I think that i sucssed to do pull request
