### ISSUE TITLE
Convert Markdown

### ISSUE THREAD

**Issue by RivkaBerlinski** [skyvar/registration#8]
Programmatically convert a markdown document to a PDF in any language.

**Comment by bdsoha** [comment]
@RivkaBerlinski you have been assigned. Good luck!

**Comment by bdsoha** [comment]
Please update your user profile based on:
> Register a GitHub account with your corporate email address (i.e. @skyvar.co.il) and your full first and last name in English.

**Comment by bdsoha** [comment]
@RivkaBerlinski  Any updates? Questions?

**Comment by RivkaBerlinski** [comment]
I want to clone my fork to the local to be enable to stage my project to the fork.
 when i run comand:
 git clone https://github.com/RivkaBerlinski/feature-convert-md-file-to-pdf.git
 I get an error:
 Cloning into 'feature-convert-md-file-to-pdf'...
fatal: unable to access 'https://github.com/RivkaBerlinski/feature-convert-md-file-to-pdf.git/': SSL certificate problem: unable to get local issuer certificate

**Comment by bdsoha** [comment]
Regarding your SSL issue:
https://netfree.link/wiki/Installation_of_certificate_in_GIT

**Comment by RivkaBerlinski** [comment]
I create pull request for my branch
can you see it?

**Comment by bdsoha** [comment]
If you see it, then I see it.
