### ISSUE TITLE
K3S

### ISSUE THREAD

**Issue by chanaSlumianski** [skyvar/registration#9]
Write a short Markdown document describing k3s:

What is it?
When should it be used?
Where can it be used?
Why should I use it?

**Comment by bdsoha** [comment]
@chanaSlumianski you have been assigned. Good luck!

**Comment by bdsoha** [comment]
Please update your user profile based on:
> Register a GitHub account with your corporate email address (i.e. @skyvar.co.il) and your full first and last name in English.

**Comment by chanaSlumianski** [comment]
I would love to hear comments 
and know what is meant by the last question
What is the additional accuracy on the description I wrote

## _Markdown document describing k3s_

## What is it?

K3s is a fully conformant production-ready Kubernetes distribution with the following changes:

- It is packaged as a single binary.
- It adds support for sqlite3 as the default storage backend. Etcd3, MySQL, and Postgres are also supported.
- It wraps Kubernetes and other components in a single, simple launcher.
- It is secure by default with reasonable defaults for lightweight environments.
- It has minimal to no OS dependencies (just a sane kernel and cgroup mounts needed).
- It eliminates the need to expose a port on Kubernetes worker nodes for the kubelet API by exposing this API to the Kubernetes control plane nodes over a websocket tunnel.

## Why should I use it?

- Production ready and secure.
- easy to install.
- half the memory. 
- all in a binary less than 100 MB.
- certified Kubernetes distribution designed for production workloads  in unattended,
remote locations or inside IoT ("Internet of Things" - Devices that are connected and can communicate with other devices) appliances.

## When should it be used?

In cases where the above benefits are important to me.

## Where can it be used?

**Comment by bdsoha** [comment]
> Where can it be used?
Refers to the IT/System/Local/Cloud environments

**Comment by chanaSlumianski** [comment]
ok

**Comment by bdsoha** [comment]
@chanaSlumianski  Any updates? Questions?

**Comment by chanaSlumianski** [comment]
now I finished to creat the image and the docker 
so now I try how to pull my file to the git

**Comment by bdsoha** [comment]
How is your task related to docker?

**Comment by chanaSlumianski** [comment]
It is true that I created a simple document 
but I wanted to know how I connect to Docker while this document describes code files

**Comment by chanaSlumianski** [comment]
I have to upload my file throuth here ?
![image](https://user-images.githubusercontent.com/127835603/225325465-fbc8d496-d303-4016-9c94-32766b999c54.png)

**Comment by chanaSlumianski** [comment]
with the add file bottun ?

**Comment by bdsoha** [comment]
> with the add file bottun ?

You need to be using `git` from your local machine.

**Comment by bdsoha** [comment]
Any updates?

**Comment by chanaSlumianski** [comment]
I created anew branch and uploaded my file but my file not appear
so I deleted the branch and creat a new 
i'm on it...
